import '../../features/assets/domain/models/machine_model.dart';
import '../../features/assets/domain/enums/department_type.dart';
import '../../features/assets/domain/enums/machine_status.dart';

const List<MachineModel> assemblyArmouringMachines = [
  // 5. Assembly & Wire Armouring Department (assembly)
  MachineModel(
    id: 'DT01',
    code: 'DT01',
    name: 'Drum Twister DT-3000',
    department: DepartmentType.assembly,
    status: MachineStatus.running,
    subCategory: 'Drum Twister',
    currentSpeedMpm: 45.0,
    totalMetersProduced: 180000.0,
  ),
  MachineModel(
    id: 'DT02',
    code: 'DT02',
    name: 'Drum Twister DT-3600',
    department: DepartmentType.assembly,
    status: MachineStatus.running,
    subCategory: 'Drum Twister',
    currentSpeedMpm: 40.0,
    totalMetersProduced: 165000.0,
  ),
  MachineModel(
    id: 'DT03',
    code: 'DT03',
    name: 'Drum Twister DT-4000',
    department: DepartmentType.assembly,
    status: MachineStatus.running,
    subCategory: 'Drum Twister',
    currentSpeedMpm: 35.0,
    totalMetersProduced: 140000.0,
  ),
  MachineModel(
    id: 'DT04',
    code: 'DT04',
    name: 'Drum Twister DT-3200',
    department: DepartmentType.assembly,
    status: MachineStatus.running,
    subCategory: 'Drum Twister',
    currentSpeedMpm: 42.0,
    totalMetersProduced: 172000.0,
  ),
  MachineModel(
    id: 'BW01',
    code: 'BW01',
    name: 'Bow Cabling Line 01',
    department: DepartmentType.assembly,
    status: MachineStatus.running,
    subCategory: 'Bow Cabling',
    currentSpeedMpm: 120.0,
    totalMetersProduced: 290000.0,
  ),

  // 6. Screening & Taping Department (screening)
  MachineModel(
    id: 'CT01',
    code: 'CT01',
    name: 'Copper Tape Line 01',
    department: DepartmentType.screening,
    status: MachineStatus.running,
    subCategory: 'Copper Tape / Mica / PPT',
    currentSpeedMpm: 160.0,
    totalMetersProduced: 310000.0,
  ),
  MachineModel(
    id: 'CT02',
    code: 'CT02',
    name: 'Copper Tape Line 02',
    department: DepartmentType.screening,
    status: MachineStatus.running,
    subCategory: 'Copper Tape / Mica / PPT',
    currentSpeedMpm: 165.0,
    totalMetersProduced: 325000.0,
  ),
  MachineModel(
    id: 'CT03',
    code: 'CT03',
    name: 'Copper Tape Line 03',
    department: DepartmentType.screening,
    status: MachineStatus.running,
    subCategory: 'Copper Tape / Mica / PPT',
    currentSpeedMpm: 155.0,
    totalMetersProduced: 295000.0,
  ),
  MachineModel(
    id: 'CW01',
    code: 'CW01',
    name: 'Copper Wire Screen Line 01',
    department: DepartmentType.screening,
    status: MachineStatus.running,
    subCategory: 'Copper Wire Screen',
    currentSpeedMpm: 110.0,
    totalMetersProduced: 240000.0,
  ),
  MachineModel(
    id: 'CW02',
    code: 'CW02',
    name: 'Copper Wire Screen Line 02',
    department: DepartmentType.screening,
    status: MachineStatus.running,
    subCategory: 'Copper Wire Screen',
    currentSpeedMpm: 115.0,
    totalMetersProduced: 250000.0,
  ),
  MachineModel(
    id: 'CW03',
    code: 'CW03',
    name: 'Copper Wire Screen Line 03',
    department: DepartmentType.screening,
    status: MachineStatus.running,
    subCategory: 'Copper Wire Screen',
    currentSpeedMpm: 108.0,
    totalMetersProduced: 235000.0,
  ),

  // 7. Tape Armouring Department (tapeArmour)
  MachineModel(
    id: 'ST01',
    code: 'ST01',
    name: 'Steel Tape Armouring Line 01',
    department: DepartmentType.tapeArmour,
    status: MachineStatus.running,
    subCategory: 'Steel Tape Armouring',
    currentSpeedMpm: 140.0,
    totalMetersProduced: 280000.0,
  ),
  MachineModel(
    id: 'ST02',
    code: 'ST02',
    name: 'Steel Tape Armouring Line 02',
    department: DepartmentType.tapeArmour,
    status: MachineStatus.running,
    subCategory: 'Steel Tape Armouring',
    currentSpeedMpm: 145.0,
    totalMetersProduced: 290000.0,
  ),
  MachineModel(
    id: 'ST03',
    code: 'ST03',
    name: 'Steel Tape Armouring Line 03',
    department: DepartmentType.tapeArmour,
    status: MachineStatus.running,
    subCategory: 'Steel Tape Armouring',
    currentSpeedMpm: 138.0,
    totalMetersProduced: 275000.0,
  ),
  MachineModel(
    id: 'ST04',
    code: 'ST04',
    name: 'Steel Tape Armouring Line 04',
    department: DepartmentType.tapeArmour,
    status: MachineStatus.running,
    subCategory: 'Steel Tape Armouring',
    currentSpeedMpm: 142.0,
    totalMetersProduced: 285000.0,
  ),
];
