import '../../features/assets/domain/models/machine_model.dart';
import '../../features/assets/domain/enums/department_type.dart';
import '../../features/assets/domain/enums/machine_status.dart';

const List<MachineModel> drawingStrandingMachines = [
  // 1. Drawing Department (drawing)
  MachineModel(
    id: 'DR01',
    code: 'DR01',
    name: 'Copper Drawing Line 01',
    department: DepartmentType.drawing,
    status: MachineStatus.running,
    subCategory: 'Copper Drawing',
    currentSpeedMpm: 1200.0,
    totalMetersProduced: 450000.0,
  ),
  MachineModel(
    id: 'DR02',
    code: 'DR02',
    name: 'Copper Drawing Line 02',
    department: DepartmentType.drawing,
    status: MachineStatus.running,
    subCategory: 'Copper Drawing',
    currentSpeedMpm: 1150.0,
    totalMetersProduced: 420000.0,
  ),
  MachineModel(
    id: 'DR03',
    code: 'DR03',
    name: 'Copper Drawing Line 03',
    department: DepartmentType.drawing,
    status: MachineStatus.idle,
    subCategory: 'Copper Drawing',
    currentSpeedMpm: 0.0,
    totalMetersProduced: 390000.0,
  ),
  MachineModel(
    id: 'DR04',
    code: 'DR04',
    name: 'Aluminum & Al-Alloy Drawing 01',
    department: DepartmentType.drawing,
    status: MachineStatus.running,
    subCategory: 'Aluminum & Al-Alloy Drawing',
    currentSpeedMpm: 950.0,
    totalMetersProduced: 310000.0,
  ),
  MachineModel(
    id: 'DR05',
    code: 'DR05',
    name: 'Aluminum & Al-Alloy Drawing 02',
    department: DepartmentType.drawing,
    status: MachineStatus.running,
    subCategory: 'Aluminum & Al-Alloy Drawing',
    currentSpeedMpm: 980.0,
    totalMetersProduced: 330000.0,
  ),
  MachineModel(
    id: 'DR06',
    code: 'DR06',
    name: 'Copper Multiwire 14-Wire Line 01',
    department: DepartmentType.drawing,
    status: MachineStatus.running,
    subCategory: 'Copper Multiwire (14 wires)',
    currentSpeedMpm: 1500.0,
    totalMetersProduced: 890000.0,
  ),
  MachineModel(
    id: 'DR07',
    code: 'DR07',
    name: 'Copper Multiwire 14-Wire Line 02',
    department: DepartmentType.drawing,
    status: MachineStatus.running,
    subCategory: 'Copper Multiwire (14 wires)',
    currentSpeedMpm: 1550.0,
    totalMetersProduced: 920000.0,
  ),

  // 2. Stranding & Bunching Department (stranding)
  MachineModel(
    id: 'RS01',
    code: 'RS01',
    name: 'Rigid Strander 61 - Line 01',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Rigid Strander 61',
    currentSpeedMpm: 180.0,
    totalMetersProduced: 125000.0,
  ),
  MachineModel(
    id: 'RS02',
    code: 'RS02',
    name: 'Rigid Strander 61 - Line 02',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Rigid Strander 61',
    currentSpeedMpm: 175.0,
    totalMetersProduced: 118000.0,
  ),
  MachineModel(
    id: 'RS03',
    code: 'RS03',
    name: 'Rigid Strander 61 - Line 03',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Rigid Strander 61',
    currentSpeedMpm: 185.0,
    totalMetersProduced: 130000.0,
  ),
  MachineModel(
    id: 'RS04',
    code: 'RS04',
    name: 'Rigid Strander 61 - Line 04',
    department: DepartmentType.stranding,
    status: MachineStatus.downtimeMaintenance,
    subCategory: 'Rigid Strander 61',
    currentSpeedMpm: 0.0,
    totalMetersProduced: 95000.0,
  ),
  MachineModel(
    id: 'CS01',
    code: 'CS01',
    name: 'Circular/Cage Strander 37 - Line 01',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Circular/Cage Strander 37',
    currentSpeedMpm: 220.0,
    totalMetersProduced: 210000.0,
  ),
  MachineModel(
    id: 'CS02',
    code: 'CS02',
    name: 'Circular/Cage Strander 37 - Line 02',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Circular/Cage Strander 37',
    currentSpeedMpm: 215.0,
    totalMetersProduced: 205000.0,
  ),
  MachineModel(
    id: 'RS05',
    code: 'RS05',
    name: 'Rigid Strander 19 - Line 05',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Rigid Strander 19',
    currentSpeedMpm: 280.0,
    totalMetersProduced: 340000.0,
  ),
  MachineModel(
    id: 'DTS01',
    code: 'DTS01',
    name: 'Double Twist Strander 7 - Line 01',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Double Twist Strander 7',
    currentSpeedMpm: 450.0,
    totalMetersProduced: 560000.0,
  ),
  MachineModel(
    id: 'BN01',
    code: 'BN01',
    name: 'Buncher 630 - Line 01',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Buncher (630)',
    currentSpeedMpm: 350.0,
    totalMetersProduced: 410000.0,
  ),
  MachineModel(
    id: 'BN02',
    code: 'BN02',
    name: 'Buncher 630 - Line 02',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Buncher (630)',
    currentSpeedMpm: 360.0,
    totalMetersProduced: 420000.0,
  ),
  MachineModel(
    id: 'BN03',
    code: 'BN03',
    name: 'Buncher 630 - Line 03',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Buncher (630)',
    currentSpeedMpm: 355.0,
    totalMetersProduced: 415000.0,
  ),
  MachineModel(
    id: 'BN04',
    code: 'BN04',
    name: 'Buncher 630 - Line 04',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Buncher (630)',
    currentSpeedMpm: 345.0,
    totalMetersProduced: 395000.0,
  ),
  MachineModel(
    id: 'BN05',
    code: 'BN05',
    name: 'Buncher 630 - Line 05',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Buncher (630)',
    currentSpeedMpm: 350.0,
    totalMetersProduced: 400000.0,
  ),
  MachineModel(
    id: 'BN06',
    code: 'BN06',
    name: 'Buncher 800 - Line 06',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Buncher (800)',
    currentSpeedMpm: 300.0,
    totalMetersProduced: 380000.0,
  ),
  MachineModel(
    id: 'BN07',
    code: 'BN07',
    name: 'Buncher 800 - Line 07',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Buncher (800)',
    currentSpeedMpm: 310.0,
    totalMetersProduced: 390000.0,
  ),
  MachineModel(
    id: 'BN08',
    code: 'BN08',
    name: 'Buncher 800 - Line 08',
    department: DepartmentType.stranding,
    status: MachineStatus.running,
    subCategory: 'Buncher (800)',
    currentSpeedMpm: 305.0,
    totalMetersProduced: 385000.0,
  ),
];
