import '../../features/assets/domain/models/machine_model.dart';
import '../../features/assets/domain/enums/department_type.dart';
import '../../features/assets/domain/enums/machine_status.dart';

const List<MachineModel> extrusionCcvMachines = [
  // 3. CCV Lines (ccv)
  MachineModel(
    id: 'CCV01',
    code: 'CCV01',
    name: 'Medium/High Voltage CCV Line 01 (500kV)',
    department: DepartmentType.ccv,
    status: MachineStatus.running,
    subCategory: 'CCV Line (Up to 500kV)',
    currentSpeedMpm: 25.0,
    totalMetersProduced: 85000.0,
  ),
  MachineModel(
    id: 'CCV02',
    code: 'CCV02',
    name: 'Medium/High Voltage CCV Line 02 (500kV)',
    department: DepartmentType.ccv,
    status: MachineStatus.running,
    subCategory: 'CCV Line (Up to 500kV)',
    currentSpeedMpm: 28.0,
    totalMetersProduced: 92000.0,
  ),
  MachineModel(
    id: 'CCV03',
    code: 'CCV03',
    name: 'Extra High Voltage CCV Line 03 (750kV)',
    department: DepartmentType.ccv,
    status: MachineStatus.running,
    subCategory: 'CCV Line (Up to 750kV)',
    currentSpeedMpm: 18.0,
    totalMetersProduced: 64000.0,
  ),
  MachineModel(
    id: 'CCV04',
    code: 'CCV04',
    name: 'Extra High Voltage CCV Line 04 (750kV)',
    department: DepartmentType.ccv,
    status: MachineStatus.downtimeProcess,
    subCategory: 'CCV Line (Up to 750kV)',
    currentSpeedMpm: 0.0,
    totalMetersProduced: 58000.0,
  ),
  MachineModel(
    id: 'CCV05',
    code: 'CCV05',
    name: 'Medium Voltage CCV Line 05',
    department: DepartmentType.ccv,
    status: MachineStatus.running,
    subCategory: 'CCV Line (Medium Voltage)',
    currentSpeedMpm: 32.0,
    totalMetersProduced: 110000.0,
  ),

  // 4. Extrusion Department (extrusion) - 11 lines EX01-EX11
  MachineModel(
    id: 'EX01',
    code: 'EX01',
    name: 'LV Extrusion Line 01 (Insulation)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 450.0,
    totalMetersProduced: 780000.0,
  ),
  MachineModel(
    id: 'EX02',
    code: 'EX02',
    name: 'LV Extrusion Line 02 (Insulation)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 460.0,
    totalMetersProduced: 810000.0,
  ),
  MachineModel(
    id: 'EX03',
    code: 'EX03',
    name: 'LV Extrusion Line 03 (Bedding)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 420.0,
    totalMetersProduced: 740000.0,
  ),
  MachineModel(
    id: 'EX04',
    code: 'EX04',
    name: 'LV Extrusion Line 04 (Jacketing)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 380.0,
    totalMetersProduced: 690000.0,
  ),
  MachineModel(
    id: 'EX05',
    code: 'EX05',
    name: 'LV Extrusion Line 05 (Jacketing)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 390.0,
    totalMetersProduced: 710000.0,
  ),
  MachineModel(
    id: 'EX06',
    code: 'EX06',
    name: 'LV Extrusion Line 06 (Insulation)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 440.0,
    totalMetersProduced: 760000.0,
  ),
  MachineModel(
    id: 'EX07',
    code: 'EX07',
    name: 'LV Extrusion Line 07 (Insulation)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 430.0,
    totalMetersProduced: 750000.0,
  ),
  MachineModel(
    id: 'EX08',
    code: 'EX08',
    name: 'LV Extrusion Line 08 (Bedding)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 410.0,
    totalMetersProduced: 720000.0,
  ),
  MachineModel(
    id: 'EX09',
    code: 'EX09',
    name: 'LV Extrusion Line 09 (Bedding)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 415.0,
    totalMetersProduced: 730000.0,
  ),
  MachineModel(
    id: 'EX10',
    code: 'EX10',
    name: 'LV Extrusion Line 10 (Jacketing)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 375.0,
    totalMetersProduced: 680000.0,
  ),
  MachineModel(
    id: 'EX11',
    code: 'EX11',
    name: 'LV Extrusion Line 11 (Jacketing)',
    department: DepartmentType.extrusion,
    status: MachineStatus.running,
    subCategory: 'Low Voltage Extrusion',
    currentSpeedMpm: 385.0,
    totalMetersProduced: 700000.0,
  ),
];
