import '../../features/assets/domain/models/machine_model.dart';
import '../../features/assets/domain/enums/department_type.dart';
import '../../features/assets/domain/enums/machine_status.dart';
import '../../features/work_orders/domain/models/work_order_model.dart';
import '../../features/work_orders/domain/enums/work_order_status.dart';
import '../../features/work_orders/domain/enums/work_order_type.dart';
import '../../features/work_orders/domain/enums/priority.dart';
import '../chronology/event_chronology.dart';

class FactorySeedData {
  static List<MachineModel> getInitialMachines() {
    return [
      // 1. Drawing Department (drawing)
      const MachineModel(
        id: 'DR01',
        code: 'DR01',
        name: 'Copper Drawing Line 01',
        department: DepartmentType.drawing,
        status: MachineStatus.running,
        subCategory: 'Copper Drawing',
        currentSpeedMpm: 1200.0,
        totalMetersProduced: 450000.0,
      ),
      const MachineModel(
        id: 'DR02',
        code: 'DR02',
        name: 'Copper Drawing Line 02',
        department: DepartmentType.drawing,
        status: MachineStatus.running,
        subCategory: 'Copper Drawing',
        currentSpeedMpm: 1150.0,
        totalMetersProduced: 420000.0,
      ),
      const MachineModel(
        id: 'DR03',
        code: 'DR03',
        name: 'Copper Drawing Line 03',
        department: DepartmentType.drawing,
        status: MachineStatus.idle,
        subCategory: 'Copper Drawing',
        currentSpeedMpm: 0.0,
        totalMetersProduced: 390000.0,
      ),
      const MachineModel(
        id: 'DR04',
        code: 'DR04',
        name: 'Aluminum & Al-Alloy Drawing 01',
        department: DepartmentType.drawing,
        status: MachineStatus.running,
        subCategory: 'Aluminum & Al-Alloy Drawing',
        currentSpeedMpm: 950.0,
        totalMetersProduced: 310000.0,
      ),
      const MachineModel(
        id: 'DR05',
        code: 'DR05',
        name: 'Aluminum & Al-Alloy Drawing 02',
        department: DepartmentType.drawing,
        status: MachineStatus.running,
        subCategory: 'Aluminum & Al-Alloy Drawing',
        currentSpeedMpm: 980.0,
        totalMetersProduced: 330000.0,
      ),
      const MachineModel(
        id: 'DR06',
        code: 'DR06',
        name: 'Copper Multiwire 14-Wire Line 01',
        department: DepartmentType.drawing,
        status: MachineStatus.running,
        subCategory: 'Copper Multiwire (14 wires)',
        currentSpeedMpm: 1500.0,
        totalMetersProduced: 890000.0,
      ),
      const MachineModel(
        id: 'DR07',
        code: 'DR07',
        name: 'Copper Multiwire 14-Wire Line 02',
        department: DepartmentType.drawing,
        status: MachineStatus.running,
        subCategory: 'Copper Multiwire (14 wires)',
        currentSpeedMpm: 1550.0,
        totalMetersProduced: 920000.0,
      ),

      // 2. Stranding & Bunching Department (stranding)
      const MachineModel(
        id: 'RS01',
        code: 'RS01',
        name: 'Rigid Strander 61 - Line 01',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Rigid Strander 61',
        currentSpeedMpm: 180.0,
        totalMetersProduced: 125000.0,
      ),
      const MachineModel(
        id: 'RS02',
        code: 'RS02',
        name: 'Rigid Strander 61 - Line 02',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Rigid Strander 61',
        currentSpeedMpm: 175.0,
        totalMetersProduced: 118000.0,
      ),
      const MachineModel(
        id: 'RS03',
        code: 'RS03',
        name: 'Rigid Strander 61 - Line 03',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Rigid Strander 61',
        currentSpeedMpm: 185.0,
        totalMetersProduced: 130000.0,
      ),
      const MachineModel(
        id: 'RS04',
        code: 'RS04',
        name: 'Rigid Strander 61 - Line 04',
        department: DepartmentType.stranding,
        status: MachineStatus.downtimeMaintenance,
        subCategory: 'Rigid Strander 61',
        currentSpeedMpm: 0.0,
        totalMetersProduced: 95000.0,
      ),
      const MachineModel(
        id: 'CS01',
        code: 'CS01',
        name: 'Circular/Cage Strander 37 - Line 01',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Circular/Cage Strander 37',
        currentSpeedMpm: 220.0,
        totalMetersProduced: 210000.0,
      ),
      const MachineModel(
        id: 'CS02',
        code: 'CS02',
        name: 'Circular/Cage Strander 37 - Line 02',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Circular/Cage Strander 37',
        currentSpeedMpm: 215.0,
        totalMetersProduced: 205000.0,
      ),
      const MachineModel(
        id: 'RS05',
        code: 'RS05',
        name: 'Rigid Strander 19 - Line 05',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Rigid Strander 19',
        currentSpeedMpm: 280.0,
        totalMetersProduced: 340000.0,
      ),
      const MachineModel(
        id: 'DTS01',
        code: 'DTS01',
        name: 'Double Twist Strander 7 - Line 01',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Double Twist Strander 7',
        currentSpeedMpm: 450.0,
        totalMetersProduced: 560000.0,
      ),
      const MachineModel(
        id: 'BN01',
        code: 'BN01',
        name: 'Buncher 630 - Line 01',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Buncher (630)',
        currentSpeedMpm: 350.0,
        totalMetersProduced: 410000.0,
      ),
      const MachineModel(
        id: 'BN02',
        code: 'BN02',
        name: 'Buncher 630 - Line 02',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Buncher (630)',
        currentSpeedMpm: 360.0,
        totalMetersProduced: 420000.0,
      ),
      const MachineModel(
        id: 'BN03',
        code: 'BN03',
        name: 'Buncher 630 - Line 03',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Buncher (630)',
        currentSpeedMpm: 355.0,
        totalMetersProduced: 415000.0,
      ),
      const MachineModel(
        id: 'BN04',
        code: 'BN04',
        name: 'Buncher 630 - Line 04',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Buncher (630)',
        currentSpeedMpm: 345.0,
        totalMetersProduced: 395000.0,
      ),
      const MachineModel(
        id: 'BN05',
        code: 'BN05',
        name: 'Buncher 630 - Line 05',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Buncher (630)',
        currentSpeedMpm: 350.0,
        totalMetersProduced: 400000.0,
      ),
      const MachineModel(
        id: 'BN06',
        code: 'BN06',
        name: 'Buncher 800 - Line 06',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Buncher (800)',
        currentSpeedMpm: 300.0,
        totalMetersProduced: 380000.0,
      ),
      const MachineModel(
        id: 'BN07',
        code: 'BN07',
        name: 'Buncher 800 - Line 07',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Buncher (800)',
        currentSpeedMpm: 310.0,
        totalMetersProduced: 390000.0,
      ),
      const MachineModel(
        id: 'BN08',
        code: 'BN08',
        name: 'Buncher 800 - Line 08',
        department: DepartmentType.stranding,
        status: MachineStatus.running,
        subCategory: 'Buncher (800)',
        currentSpeedMpm: 305.0,
        totalMetersProduced: 385000.0,
      ),

      // 3. CCV Lines (ccv)
      const MachineModel(
        id: 'CCV01',
        code: 'CCV01',
        name: 'Medium/High Voltage CCV Line 01 (500kV)',
        department: DepartmentType.ccv,
        status: MachineStatus.running,
        subCategory: 'CCV Line (Up to 500kV)',
        currentSpeedMpm: 25.0,
        totalMetersProduced: 85000.0,
      ),
      const MachineModel(
        id: 'CCV02',
        code: 'CCV02',
        name: 'Medium/High Voltage CCV Line 02 (500kV)',
        department: DepartmentType.ccv,
        status: MachineStatus.running,
        subCategory: 'CCV Line (Up to 500kV)',
        currentSpeedMpm: 28.0,
        totalMetersProduced: 92000.0,
      ),
      const MachineModel(
        id: 'CCV03',
        code: 'CCV03',
        name: 'Extra High Voltage CCV Line 03 (750kV)',
        department: DepartmentType.ccv,
        status: MachineStatus.running,
        subCategory: 'CCV Line (Up to 750kV)',
        currentSpeedMpm: 18.0,
        totalMetersProduced: 64000.0,
      ),
      const MachineModel(
        id: 'CCV04',
        code: 'CCV04',
        name: 'Extra High Voltage CCV Line 04 (750kV)',
        department: DepartmentType.ccv,
        status: MachineStatus.downtimeProcess,
        subCategory: 'CCV Line (Up to 750kV)',
        currentSpeedMpm: 0.0,
        totalMetersProduced: 58000.0,
      ),
      const MachineModel(
        id: 'CCV05',
        code: 'CCV05',
        name: 'Medium Voltage CCV Line 05',
        department: DepartmentType.ccv,
        status: MachineStatus.running,
        subCategory: 'CCV Line (Medium Voltage)',
        currentSpeedMpm: 32.0,
        totalMetersProduced: 110000.0,
      ),

      // 4. Extrusion Department (extrusion) - 11 lines EX01-EX11
      const MachineModel(
        id: 'EX01',
        code: 'EX01',
        name: 'LV Extrusion Line 01 (Insulation)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 450.0,
        totalMetersProduced: 780000.0,
      ),
      const MachineModel(
        id: 'EX02',
        code: 'EX02',
        name: 'LV Extrusion Line 02 (Insulation)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 460.0,
        totalMetersProduced: 810000.0,
      ),
      const MachineModel(
        id: 'EX03',
        code: 'EX03',
        name: 'LV Extrusion Line 03 (Bedding)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 420.0,
        totalMetersProduced: 740000.0,
      ),
      const MachineModel(
        id: 'EX04',
        code: 'EX04',
        name: 'LV Extrusion Line 04 (Jacketing)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 380.0,
        totalMetersProduced: 690000.0,
      ),
      const MachineModel(
        id: 'EX05',
        code: 'EX05',
        name: 'LV Extrusion Line 05 (Jacketing)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 390.0,
        totalMetersProduced: 710000.0,
      ),
      const MachineModel(
        id: 'EX06',
        code: 'EX06',
        name: 'LV Extrusion Line 06 (Insulation)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 440.0,
        totalMetersProduced: 760000.0,
      ),
      const MachineModel(
        id: 'EX07',
        code: 'EX07',
        name: 'LV Extrusion Line 07 (Insulation)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 430.0,
        totalMetersProduced: 750000.0,
      ),
      const MachineModel(
        id: 'EX08',
        code: 'EX08',
        name: 'LV Extrusion Line 08 (Bedding)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 410.0,
        totalMetersProduced: 720000.0,
      ),
      const MachineModel(
        id: 'EX09',
        code: 'EX09',
        name: 'LV Extrusion Line 09 (Bedding)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 415.0,
        totalMetersProduced: 730000.0,
      ),
      const MachineModel(
        id: 'EX10',
        code: 'EX10',
        name: 'LV Extrusion Line 10 (Jacketing)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 375.0,
        totalMetersProduced: 680000.0,
      ),
      const MachineModel(
        id: 'EX11',
        code: 'EX11',
        name: 'LV Extrusion Line 11 (Jacketing)',
        department: DepartmentType.extrusion,
        status: MachineStatus.running,
        subCategory: 'Low Voltage Extrusion',
        currentSpeedMpm: 385.0,
        totalMetersProduced: 700000.0,
      ),

      // 5. Assembly & Wire Armouring Department (assembly)
      const MachineModel(
        id: 'DT01',
        code: 'DT01',
        name: 'Drum Twister DT-3000',
        department: DepartmentType.assembly,
        status: MachineStatus.running,
        subCategory: 'Drum Twister',
        currentSpeedMpm: 45.0,
        totalMetersProduced: 180000.0,
      ),
      const MachineModel(
        id: 'DT02',
        code: 'DT02',
        name: 'Drum Twister DT-3600',
        department: DepartmentType.assembly,
        status: MachineStatus.running,
        subCategory: 'Drum Twister',
        currentSpeedMpm: 40.0,
        totalMetersProduced: 165000.0,
      ),
      const MachineModel(
        id: 'DT03',
        code: 'DT03',
        name: 'Drum Twister DT-4000',
        department: DepartmentType.assembly,
        status: MachineStatus.running,
        subCategory: 'Drum Twister',
        currentSpeedMpm: 35.0,
        totalMetersProduced: 140000.0,
      ),
      const MachineModel(
        id: 'DT04',
        code: 'DT04',
        name: 'Drum Twister DT-3200',
        department: DepartmentType.assembly,
        status: MachineStatus.running,
        subCategory: 'Drum Twister',
        currentSpeedMpm: 42.0,
        totalMetersProduced: 172000.0,
      ),
      const MachineModel(
        id: 'BW01',
        code: 'BW01',
        name: 'Bow Cabling Line 01',
        department: DepartmentType.assembly,
        status: MachineStatus.running,
        subCategory: 'Bow Cabling',
        currentSpeedMpm: 120.0,
        totalMetersProduced: 290000.0,
      ),

      // 6. Screening & Taping Department (screening)
      const MachineModel(
        id: 'CT01',
        code: 'CT01',
        name: 'Copper Tape Line 01',
        department: DepartmentType.screening,
        status: MachineStatus.running,
        subCategory: 'Copper Tape / Mica / PPT',
        currentSpeedMpm: 160.0,
        totalMetersProduced: 310000.0,
      ),
      const MachineModel(
        id: 'CT02',
        code: 'CT02',
        name: 'Copper Tape Line 02',
        department: DepartmentType.screening,
        status: MachineStatus.running,
        subCategory: 'Copper Tape / Mica / PPT',
        currentSpeedMpm: 165.0,
        totalMetersProduced: 325000.0,
      ),
      const MachineModel(
        id: 'CT03',
        code: 'CT03',
        name: 'Copper Tape Line 03',
        department: DepartmentType.screening,
        status: MachineStatus.running,
        subCategory: 'Copper Tape / Mica / PPT',
        currentSpeedMpm: 155.0,
        totalMetersProduced: 295000.0,
      ),
      const MachineModel(
        id: 'CW01',
        code: 'CW01',
        name: 'Copper Wire Screen Line 01',
        department: DepartmentType.screening,
        status: MachineStatus.running,
        subCategory: 'Copper Wire Screen',
        currentSpeedMpm: 110.0,
        totalMetersProduced: 240000.0,
      ),
      const MachineModel(
        id: 'CW02',
        code: 'CW02',
        name: 'Copper Wire Screen Line 02',
        department: DepartmentType.screening,
        status: MachineStatus.running,
        subCategory: 'Copper Wire Screen',
        currentSpeedMpm: 115.0,
        totalMetersProduced: 250000.0,
      ),
      const MachineModel(
        id: 'CW03',
        code: 'CW03',
        name: 'Copper Wire Screen Line 03',
        department: DepartmentType.screening,
        status: MachineStatus.running,
        subCategory: 'Copper Wire Screen',
        currentSpeedMpm: 108.0,
        totalMetersProduced: 235000.0,
      ),

      // 7. Tape Armouring Department (tapeArmour)
      const MachineModel(
        id: 'ST01',
        code: 'ST01',
        name: 'Steel Tape Armouring Line 01',
        department: DepartmentType.tapeArmour,
        status: MachineStatus.running,
        subCategory: 'Steel Tape Armouring',
        currentSpeedMpm: 140.0,
        totalMetersProduced: 280000.0,
      ),
      const MachineModel(
        id: 'ST02',
        code: 'ST02',
        name: 'Steel Tape Armouring Line 02',
        department: DepartmentType.tapeArmour,
        status: MachineStatus.running,
        subCategory: 'Steel Tape Armouring',
        currentSpeedMpm: 145.0,
        totalMetersProduced: 290000.0,
      ),
      const MachineModel(
        id: 'ST03',
        code: 'ST03',
        name: 'Steel Tape Armouring Line 03',
        department: DepartmentType.tapeArmour,
        status: MachineStatus.running,
        subCategory: 'Steel Tape Armouring',
        currentSpeedMpm: 138.0,
        totalMetersProduced: 275000.0,
      ),
      const MachineModel(
        id: 'ST04',
        code: 'ST04',
        name: 'Steel Tape Armouring Line 04',
        department: DepartmentType.tapeArmour,
        status: MachineStatus.running,
        subCategory: 'Steel Tape Armouring',
        currentSpeedMpm: 142.0,
        totalMetersProduced: 285000.0,
      ),
    ];
  }

  static List<WorkOrderModel> getInitialWorkOrders() {
    final now = DateTime.now();
    return [
      // 1. Electrical Maintenance Task 01 (Assigned to Tariq Al-Mansoor)
      WorkOrderModel(
        id: 'WO-ELEC-001',
        title: 'عطل في درايف محرك السحب الرئيسي (Inverter Overcurrent)',
        description: 'فصل مفاجئ لمحرك خط السحب مع ظهور إنذار Overcurrent على شاشة الإنفرتر الرئيسي. يلزم فحص ملفات المحرك ووحدة التحكم.',
        machineId: 'DR01',
        type: WorkOrderType.breakdown,
        status: WorkOrderStatus.assigned,
        priority: Priority.critical,
        assignedToTechnicianId: 'usr-tech-elec-02',
        assignedBySupervisorId: 'usr-maint-sup-04',
        createdAt: now.subtract(const Duration(hours: 2)),
        chronology: EventChronology.fromDateTime(now.subtract(const Duration(hours: 2))),
      ),

      // 2. Electrical Maintenance Task 02 (In Progress - Tariq Al-Mansoor)
      WorkOrderModel(
        id: 'WO-ELEC-002',
        title: 'استبدال حساس حرارة (Thermocouple) رأس البثق Zone 3',
        description: 'تذبذب مستمر في قراءة درجات الحرارة لـ Zone 3 بخط العزل الرئيسي مما يؤثر على لزوجة المادة العازلة.',
        machineId: 'EX01',
        type: WorkOrderType.corrective,
        status: WorkOrderStatus.inProgress,
        priority: Priority.high,
        assignedToTechnicianId: 'usr-tech-elec-02',
        assignedBySupervisorId: 'usr-maint-sup-04',
        createdAt: now.subtract(const Duration(hours: 5)),
        startedAt: now.subtract(const Duration(minutes: 45)),
        chronology: EventChronology.fromDateTime(now.subtract(const Duration(hours: 5))),
      ),

      // 3. Mechanical Maintenance Task 01 (Assigned to Samir Fawzy)
      WorkOrderModel(
        id: 'WO-MECH-001',
        title: 'اهتزاز غير طبيعي وصوت احتكاك في رولمان بلي قفص الجدل',
        description: 'رصد صوت احتكاك وارتفاع في حرارة كرسي التحميل الخلفي لقفص الجدل Rigid Strander 61. يلزم فحص المحامل والتشحيم فوراً.',
        machineId: 'RS01',
        type: WorkOrderType.breakdown,
        status: WorkOrderStatus.assigned,
        priority: Priority.critical,
        assignedToTechnicianId: 'usr-tech-mech-03',
        assignedBySupervisorId: 'usr-maint-sup-04',
        createdAt: now.subtract(const Duration(hours: 1, minutes: 30)),
        chronology: EventChronology.fromDateTime(now.subtract(const Duration(hours: 1, minutes: 30))),
      ),

      // 4. Mechanical Maintenance Task 02 (In Progress - Samir Fawzy)
      WorkOrderModel(
        id: 'WO-MECH-002',
        title: 'صيانة وقائية وفحص منظومة الشد الهيدروليكي لخط التدريع',
        description: 'استبدال مانع تسرب الزيت الهيدروليكي وضبط ضغط البساتم لشداد خط التكفيل بالشريط الفولاذي.',
        machineId: 'ST01',
        type: WorkOrderType.preventive,
        status: WorkOrderStatus.inProgress,
        priority: Priority.medium,
        assignedToTechnicianId: 'usr-tech-mech-03',
        assignedBySupervisorId: 'usr-maint-sup-04',
        createdAt: now.subtract(const Duration(hours: 6)),
        startedAt: now.subtract(const Duration(hours: 2)),
        chronology: EventChronology.fromDateTime(now.subtract(const Duration(hours: 6))),
      ),

      // 5. Unassigned ticket for Drawing Department (Demonstrating department isolation)
      WorkOrderModel(
        id: 'WO-DR-003',
        title: 'فحص منظومة تبريد سائل السحب وإزالة الرواسب',
        description: 'انسداد جزئي في دورة سائل التبريد المستحلب لخط سحب النحاس 02، بانتظار توزيع المهندس للفني المختص.',
        machineId: 'DR02',
        type: WorkOrderType.corrective,
        status: WorkOrderStatus.pending,
        priority: Priority.medium,
        assignedToTechnicianId: null,
        assignedBySupervisorId: null,
        createdAt: now.subtract(const Duration(hours: 4)),
        chronology: EventChronology.fromDateTime(now.subtract(const Duration(hours: 4))),
      ),
    ];
  }
}
