// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUEOB0uZrb9LBM8eWtFaFoab39cJcG_UE',
    appId: '1:23972016733:web:0526ec8e29ab58197093b4',
    messagingSenderId: '23972016733',
    projectId: 'cmms-cable-app',
    authDomain: 'cmms-cable-app.firebaseapp.com',
    storageBucket: 'cmms-cable-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaAIv7AVgLEtHMvzi26XNZwkXUN66bue4',
    appId: '1:23972016733:android:d3577629101f12de7093b4',
    messagingSenderId: '23972016733',
    projectId: 'cmms-cable-app',
    storageBucket: 'cmms-cable-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA732HKnMfs1Fzcp1dvv_QLNLyOhhR8-vo',
    appId: '1:23972016733:ios:d69dd0fc9165c1277093b4',
    messagingSenderId: '23972016733',
    projectId: 'cmms-cable-app',
    storageBucket: 'cmms-cable-app.firebasestorage.app',
    iosBundleId: 'com.cablecmms.orningAndEveningRemembrances',
  );
}
